module.exports = {
    url: 'https://alpha.yoodlize.com/',
    elements: {
        tools: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[1]',
        gear: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[2]',
        electronics: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[3]',
        wedding: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[4]',
        recreational: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[5]',
        clothing: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[6]',
        kitchen: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[7]',
        games: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[8]',
        lawn: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[9]',
        sporting: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[10]',
        video: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[11]',
        venues: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[12]',
        experts: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[13]',
        experiences: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[14]',
        misc: '(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[15]',
        browseTools: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[1]',
        browseGear: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[2]',
        browseElectronics: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[3]',
        browseWedding: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[4]',
        browseRecreational: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[5]',
        browseClothing: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[6]',
        browseKitchen: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[7]',
        browseGames: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[8]',
        browseLawn: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[9]',
        browseSporting: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[10]',
        browseVideo: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[11]',
        browseVenues: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[12]',
        browseExperts: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[13]',
        browseExperiences: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[14]',
        browseMusic: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[15]',
        browseMisc: '(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[16]',
        category: '//div[@class="sc-jKVCRD jSqgxr"]',
    }
}